<<<<<<< HEAD
#index:
#    path: /
#    controller: App\Controller\ArticleController::homepage
=======
index:
    path: /
    controller: App\Controller\ArticleController::homepage
>>>>>>> e8534e98c0d4f8ebb5e48e892df3f6ab0c04b830
